// Code generated by wsdl2go. DO NOT EDIT.

package geowssoapbinding

import (
	"github.com/fiorix/wsdl2go/soap"
)

// Namespace was auto-generated from WSDL.
var Namespace = "http://katastr.cuzk.cz/geows/v2.2"

// NewGeo creates an initializes a Geo.
func NewGeo(cli *soap.Client) Geo {
	return &geo{cli}
}

// Geo was auto-generated from WSDL
// and defines interface for the remote service. Useful for testing.
type Geo interface {
	// DetailRizeniPM was auto-generated from WSDL.
	DetailRizeniPM(DetailRizeniPMRequest *DetailRizeniPMRequest) (*DetailRizeniPMResponse, error)

	// ExportVF was auto-generated from WSDL.
	ExportVF(ExportVFRequest *ExportVFRequest) (*ExportVFResponse, error)

	// ExportVFStatus was auto-generated from WSDL.
	ExportVFStatus(ExportVFStatusRequest *ExportVFStatusRequest) (*ExportVFStatusResponse, error)

	// MylneRizeniPM was auto-generated from WSDL.
	MylneRizeniPM(MylneRizeniPMRequest *MylneRizeniPMRequest) (*MylneRizeniPMResponse, error)

	// SeznamRizeniPM was auto-generated from WSDL.
	SeznamRizeniPM(SeznamRizeniPMRequest *SeznamRizeniPMRequest) (*SeznamRizeniPMResponse, error)

	// VytvorRezervaciPrvku was auto-generated from WSDL.
	VytvorRezervaciPrvku(VytvorRezervaciPrvkuRequest *VytvorRezervaciPrvkuRequest) (*VytvorRezervaciPrvkuResponse, error)

	// VytvorRezervaciZPMZ was auto-generated from WSDL.
	VytvorRezervaciZPMZ(VytvorRezervaciZPMZRequest *VytvorRezervaciZPMZRequest) (*VytvorRezervaciZPMZResponse, error)

	// ZalozNavrhZDP was auto-generated from WSDL.
	ZalozNavrhZDP(ZalozNavrhZDPRequest *ZalozNavrhZDPRequest) (*ZalozNavrhZDPResponse, error)

	// ZalozNavrhZPG was auto-generated from WSDL.
	ZalozNavrhZPG(ZalozNavrhZPGRequest *ZalozNavrhZPGRequest) (*ZalozNavrhZPGResponse, error)

	// ZalozRizeniPM was auto-generated from WSDL.
	ZalozRizeniPM(ZalozRizeniPMRequest *ZalozRizeniPMRequest) (*ZalozRizeniPMResponse, error)

	// ZrusRezervaciPrvku was auto-generated from WSDL.
	ZrusRezervaciPrvku(ZrusRezervaciPrvkuRequest *ZrusRezervaciPrvkuRequest) (*ZrusRezervaciPrvkuResponse, error)

	// ZrusRezervaciZPMZ was auto-generated from WSDL.
	ZrusRezervaciZPMZ(ZrusRezervaciZPMZRequest *ZrusRezervaciZPMZRequest) (*ZrusRezervaciZPMZResponse, error)
}

// Operation wrapper for DetailRizeniPM.
// OperationDetailRizeniPMRequest was auto-generated from WSDL.
type OperationDetailRizeniPMRequest struct {
	Input *DetailRizeniPMRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for DetailRizeniPM.
// OperationDetailRizeniPMResponse was auto-generated from WSDL.
type OperationDetailRizeniPMResponse struct {
	Output *DetailRizeniPMResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for ExportVF.
// OperationExportVFRequest was auto-generated from WSDL.
type OperationExportVFRequest struct {
	Input *ExportVFRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for ExportVF.
// OperationExportVFResponse was auto-generated from WSDL.
type OperationExportVFResponse struct {
	Output *ExportVFResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for ExportVFStatus.
// OperationExportVFStatusRequest was auto-generated from WSDL.
type OperationExportVFStatusRequest struct {
	Input *ExportVFStatusRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for ExportVFStatus.
// OperationExportVFStatusResponse was auto-generated from WSDL.
type OperationExportVFStatusResponse struct {
	Output *ExportVFStatusResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for MylneRizeniPM.
// OperationMylneRizeniPMRequest was auto-generated from WSDL.
type OperationMylneRizeniPMRequest struct {
	Input *MylneRizeniPMRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for MylneRizeniPM.
// OperationMylneRizeniPMResponse was auto-generated from WSDL.
type OperationMylneRizeniPMResponse struct {
	Output *MylneRizeniPMResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamRizeniPM.
// OperationSeznamRizeniPMRequest was auto-generated from WSDL.
type OperationSeznamRizeniPMRequest struct {
	Input *SeznamRizeniPMRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamRizeniPM.
// OperationSeznamRizeniPMResponse was auto-generated from WSDL.
type OperationSeznamRizeniPMResponse struct {
	Output *SeznamRizeniPMResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for VytvorRezervaciPrvku.
// OperationVytvorRezervaciPrvkuRequest was auto-generated from
// WSDL.
type OperationVytvorRezervaciPrvkuRequest struct {
	Input *VytvorRezervaciPrvkuRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for VytvorRezervaciPrvku.
// OperationVytvorRezervaciPrvkuResponse was auto-generated from
// WSDL.
type OperationVytvorRezervaciPrvkuResponse struct {
	Output *VytvorRezervaciPrvkuResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for VytvorRezervaciZPMZ.
// OperationVytvorRezervaciZPMZRequest was auto-generated from
// WSDL.
type OperationVytvorRezervaciZPMZRequest struct {
	Input *VytvorRezervaciZPMZRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for VytvorRezervaciZPMZ.
// OperationVytvorRezervaciZPMZResponse was auto-generated from
// WSDL.
type OperationVytvorRezervaciZPMZResponse struct {
	Output *VytvorRezervaciZPMZResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for ZalozNavrhZDP.
// OperationZalozNavrhZDPRequest was auto-generated from WSDL.
type OperationZalozNavrhZDPRequest struct {
	Input *ZalozNavrhZDPRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for ZalozNavrhZDP.
// OperationZalozNavrhZDPResponse was auto-generated from WSDL.
type OperationZalozNavrhZDPResponse struct {
	Output *ZalozNavrhZDPResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for ZalozNavrhZPG.
// OperationZalozNavrhZPGRequest was auto-generated from WSDL.
type OperationZalozNavrhZPGRequest struct {
	Input *ZalozNavrhZPGRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for ZalozNavrhZPG.
// OperationZalozNavrhZPGResponse was auto-generated from WSDL.
type OperationZalozNavrhZPGResponse struct {
	Output *ZalozNavrhZPGResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for ZalozRizeniPM.
// OperationZalozRizeniPMRequest was auto-generated from WSDL.
type OperationZalozRizeniPMRequest struct {
	Input *ZalozRizeniPMRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for ZalozRizeniPM.
// OperationZalozRizeniPMResponse was auto-generated from WSDL.
type OperationZalozRizeniPMResponse struct {
	Output *ZalozRizeniPMResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for ZrusRezervaciPrvku.
// OperationZrusRezervaciPrvkuRequest was auto-generated from WSDL.
type OperationZrusRezervaciPrvkuRequest struct {
	Input *ZrusRezervaciPrvkuRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for ZrusRezervaciPrvku.
// OperationZrusRezervaciPrvkuResponse was auto-generated from
// WSDL.
type OperationZrusRezervaciPrvkuResponse struct {
	Output *ZrusRezervaciPrvkuResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for ZrusRezervaciZPMZ.
// OperationZrusRezervaciZPMZRequest was auto-generated from WSDL.
type OperationZrusRezervaciZPMZRequest struct {
	Input *ZrusRezervaciZPMZRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for ZrusRezervaciZPMZ.
// OperationZrusRezervaciZPMZResponse was auto-generated from WSDL.
type OperationZrusRezervaciZPMZResponse struct {
	Output *ZrusRezervaciZPMZResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// geo implements the Geo interface.
type geo struct {
	cli *soap.Client
}

// DetailRizeniPM was auto-generated from WSDL.
func (p *geo) DetailRizeniPM(DetailRizeniPMRequest *DetailRizeniPMRequest) (*DetailRizeniPMResponse, error) {
	α := struct {
		OperationDetailRizeniPMRequest `xml:"tns:detailRizeniPM"`
	}{
		OperationDetailRizeniPMRequest{
			DetailRizeniPMRequest,
		},
	}

	γ := struct {
		OperationDetailRizeniPMResponse `xml:"detailRizeniPMResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/detailRizeniPM", α, &γ); err != nil {
		return nil, err
	}
	return γ.DetailRizeniPMResponse, nil
}

// ExportVF was auto-generated from WSDL.
func (p *geo) ExportVF(ExportVFRequest *ExportVFRequest) (*ExportVFResponse, error) {
	α := struct {
		OperationExportVFRequest `xml:"tns:exportVF"`
	}{
		OperationExportVFRequest{
			ExportVFRequest,
		},
	}

	γ := struct {
		OperationExportVFResponse `xml:"exportVFResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/exportNVF", α, &γ); err != nil {
		return nil, err
	}
	return γ.ExportVFResponse, nil
}

// ExportVFStatus was auto-generated from WSDL.
func (p *geo) ExportVFStatus(ExportVFStatusRequest *ExportVFStatusRequest) (*ExportVFStatusResponse, error) {
	α := struct {
		OperationExportVFStatusRequest `xml:"tns:exportVFStatus"`
	}{
		OperationExportVFStatusRequest{
			ExportVFStatusRequest,
		},
	}

	γ := struct {
		OperationExportVFStatusResponse `xml:"exportVFStatusResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/exportVFStatus", α, &γ); err != nil {
		return nil, err
	}
	return γ.ExportVFStatusResponse, nil
}

// MylneRizeniPM was auto-generated from WSDL.
func (p *geo) MylneRizeniPM(MylneRizeniPMRequest *MylneRizeniPMRequest) (*MylneRizeniPMResponse, error) {
	α := struct {
		OperationMylneRizeniPMRequest `xml:"tns:mylneRizeniPM"`
	}{
		OperationMylneRizeniPMRequest{
			MylneRizeniPMRequest,
		},
	}

	γ := struct {
		OperationMylneRizeniPMResponse `xml:"mylneRizeniPMResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/mylneRizeniPM", α, &γ); err != nil {
		return nil, err
	}
	return γ.MylneRizeniPMResponse, nil
}

// SeznamRizeniPM was auto-generated from WSDL.
func (p *geo) SeznamRizeniPM(SeznamRizeniPMRequest *SeznamRizeniPMRequest) (*SeznamRizeniPMResponse, error) {
	α := struct {
		OperationSeznamRizeniPMRequest `xml:"tns:seznamRizeniPM"`
	}{
		OperationSeznamRizeniPMRequest{
			SeznamRizeniPMRequest,
		},
	}

	γ := struct {
		OperationSeznamRizeniPMResponse `xml:"seznamRizeniPMResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/seznamRizeniPM", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamRizeniPMResponse, nil
}

// VytvorRezervaciPrvku was auto-generated from WSDL.
func (p *geo) VytvorRezervaciPrvku(VytvorRezervaciPrvkuRequest *VytvorRezervaciPrvkuRequest) (*VytvorRezervaciPrvkuResponse, error) {
	α := struct {
		OperationVytvorRezervaciPrvkuRequest `xml:"tns:vytvorRezervaciPrvku"`
	}{
		OperationVytvorRezervaciPrvkuRequest{
			VytvorRezervaciPrvkuRequest,
		},
	}

	γ := struct {
		OperationVytvorRezervaciPrvkuResponse `xml:"vytvorRezervaciPrvkuResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/vytvorRezervaciPrvku", α, &γ); err != nil {
		return nil, err
	}
	return γ.VytvorRezervaciPrvkuResponse, nil
}

// VytvorRezervaciZPMZ was auto-generated from WSDL.
func (p *geo) VytvorRezervaciZPMZ(VytvorRezervaciZPMZRequest *VytvorRezervaciZPMZRequest) (*VytvorRezervaciZPMZResponse, error) {
	α := struct {
		OperationVytvorRezervaciZPMZRequest `xml:"tns:vytvorRezervaciZPMZ"`
	}{
		OperationVytvorRezervaciZPMZRequest{
			VytvorRezervaciZPMZRequest,
		},
	}

	γ := struct {
		OperationVytvorRezervaciZPMZResponse `xml:"vytvorRezervaciZPMZResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/vytvorRezervaciZPMZ", α, &γ); err != nil {
		return nil, err
	}
	return γ.VytvorRezervaciZPMZResponse, nil
}

// ZalozNavrhZDP was auto-generated from WSDL.
func (p *geo) ZalozNavrhZDP(ZalozNavrhZDPRequest *ZalozNavrhZDPRequest) (*ZalozNavrhZDPResponse, error) {
	α := struct {
		OperationZalozNavrhZDPRequest `xml:"tns:zalozNavrhZDP"`
	}{
		OperationZalozNavrhZDPRequest{
			ZalozNavrhZDPRequest,
		},
	}

	γ := struct {
		OperationZalozNavrhZDPResponse `xml:"zalozNavrhZDPResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/zalozNavrhZDP", α, &γ); err != nil {
		return nil, err
	}
	return γ.ZalozNavrhZDPResponse, nil
}

// ZalozNavrhZPG was auto-generated from WSDL.
func (p *geo) ZalozNavrhZPG(ZalozNavrhZPGRequest *ZalozNavrhZPGRequest) (*ZalozNavrhZPGResponse, error) {
	α := struct {
		OperationZalozNavrhZPGRequest `xml:"tns:zalozNavrhZPG"`
	}{
		OperationZalozNavrhZPGRequest{
			ZalozNavrhZPGRequest,
		},
	}

	γ := struct {
		OperationZalozNavrhZPGResponse `xml:"zalozNavrhZPGResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/zalozNavrhZPG", α, &γ); err != nil {
		return nil, err
	}
	return γ.ZalozNavrhZPGResponse, nil
}

// ZalozRizeniPM was auto-generated from WSDL.
func (p *geo) ZalozRizeniPM(ZalozRizeniPMRequest *ZalozRizeniPMRequest) (*ZalozRizeniPMResponse, error) {
	α := struct {
		OperationZalozRizeniPMRequest `xml:"tns:zalozRizeniPM"`
	}{
		OperationZalozRizeniPMRequest{
			ZalozRizeniPMRequest,
		},
	}

	γ := struct {
		OperationZalozRizeniPMResponse `xml:"zalozRizeniPMResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/zalozRizeniPM", α, &γ); err != nil {
		return nil, err
	}
	return γ.ZalozRizeniPMResponse, nil
}

// ZrusRezervaciPrvku was auto-generated from WSDL.
func (p *geo) ZrusRezervaciPrvku(ZrusRezervaciPrvkuRequest *ZrusRezervaciPrvkuRequest) (*ZrusRezervaciPrvkuResponse, error) {
	α := struct {
		OperationZrusRezervaciPrvkuRequest `xml:"tns:zrusRezervaciPrvku"`
	}{
		OperationZrusRezervaciPrvkuRequest{
			ZrusRezervaciPrvkuRequest,
		},
	}

	γ := struct {
		OperationZrusRezervaciPrvkuResponse `xml:"zrusRezervaciPrvkuResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/zrusRezervaciPrvku", α, &γ); err != nil {
		return nil, err
	}
	return γ.ZrusRezervaciPrvkuResponse, nil
}

// ZrusRezervaciZPMZ was auto-generated from WSDL.
func (p *geo) ZrusRezervaciZPMZ(ZrusRezervaciZPMZRequest *ZrusRezervaciZPMZRequest) (*ZrusRezervaciZPMZResponse, error) {
	α := struct {
		OperationZrusRezervaciZPMZRequest `xml:"tns:zrusRezervaciZPMZ"`
	}{
		OperationZrusRezervaciZPMZRequest{
			ZrusRezervaciZPMZRequest,
		},
	}

	γ := struct {
		OperationZrusRezervaciZPMZResponse `xml:"zrusRezervaciZPMZResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/geows/zrusRezervaciZPMZ", α, &γ); err != nil {
		return nil, err
	}
	return γ.ZrusRezervaciZPMZResponse, nil
}
