// Code generated by wsdl2go. DO NOT EDIT.

package vyhledatsoapbinding

import (
	"github.com/fiorix/wsdl2go/soap"
)

// Namespace was auto-generated from WSDL.
var Namespace = "http://katastr.cuzk.cz/vyhledat/v2.8"

// NewVyhledat creates an initializes a Vyhledat.
func NewVyhledat(cli *soap.Client) Vyhledat {
	return &vyhledat{cli}
}

// Vyhledat was auto-generated from WSDL
// and defines interface for the remote service. Useful for testing.
type Vyhledat interface {
	// NajdiJednotku was auto-generated from WSDL.
	NajdiJednotku(NajdiJednotkuRequest *NajdiJednotkuRequest) (*NajdiJednotkuResponse, error)

	// NajdiListinuVeSbirceListin was auto-generated from WSDL.
	NajdiListinuVeSbirceListin(NajdiListinuVeSbirceListinRequest *NajdiListinuVeSbirceListinRequest) (*NajdiListinuVeSbirceListinResponse, error)

	// NajdiOS was auto-generated from WSDL.
	NajdiOS(NajdiOSRequest *NajdiOSRequest) (*NajdiOSResponse, error)

	// NajdiParcelu was auto-generated from WSDL.
	NajdiParcelu(NajdiParceluRequest *NajdiParceluRequest) (*NajdiParceluResponse, error)

	// NajdiPravoStavby was auto-generated from WSDL.
	NajdiPravoStavby(NajdiPravoStavbyRequest *NajdiPravoStavbyRequest) (*NajdiPravoStavbyResponse, error)

	// NajdiRizeni was auto-generated from WSDL.
	NajdiRizeni(NajdiRizeniRequest *NajdiRizeniRequest) (*NajdiRizeniResponse, error)

	// NajdiStavbu was auto-generated from WSDL.
	NajdiStavbu(NajdiStavbuRequest *NajdiStavbuRequest) (*NajdiStavbuResponse, error)
}

// Operation wrapper for NajdiJednotku.
// OperationNajdiJednotkuRequest was auto-generated from WSDL.
type OperationNajdiJednotkuRequest struct {
	Input *NajdiJednotkuRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for NajdiJednotku.
// OperationNajdiJednotkuResponse was auto-generated from WSDL.
type OperationNajdiJednotkuResponse struct {
	Output *NajdiJednotkuResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for NajdiListinuVeSbirceListin.
// OperationNajdiListinuVeSbirceListinRequest was auto-generated
// from WSDL.
type OperationNajdiListinuVeSbirceListinRequest struct {
	Input *NajdiListinuVeSbirceListinRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for NajdiListinuVeSbirceListin.
// OperationNajdiListinuVeSbirceListinResponse was auto-generated
// from WSDL.
type OperationNajdiListinuVeSbirceListinResponse struct {
	Output *NajdiListinuVeSbirceListinResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for NajdiOS.
// OperationNajdiOSRequest was auto-generated from WSDL.
type OperationNajdiOSRequest struct {
	Input *NajdiOSRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for NajdiOS.
// OperationNajdiOSResponse was auto-generated from WSDL.
type OperationNajdiOSResponse struct {
	Output *NajdiOSResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for NajdiParcelu.
// OperationNajdiParceluRequest was auto-generated from WSDL.
type OperationNajdiParceluRequest struct {
	Input *NajdiParceluRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for NajdiParcelu.
// OperationNajdiParceluResponse was auto-generated from WSDL.
type OperationNajdiParceluResponse struct {
	Output *NajdiParceluResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for NajdiPravoStavby.
// OperationNajdiPravoStavbyRequest was auto-generated from WSDL.
type OperationNajdiPravoStavbyRequest struct {
	Input *NajdiPravoStavbyRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for NajdiPravoStavby.
// OperationNajdiPravoStavbyResponse was auto-generated from WSDL.
type OperationNajdiPravoStavbyResponse struct {
	Output *NajdiPravoStavbyResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for NajdiRizeni.
// OperationNajdiRizeniRequest was auto-generated from WSDL.
type OperationNajdiRizeniRequest struct {
	Input *NajdiRizeniRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for NajdiRizeni.
// OperationNajdiRizeniResponse was auto-generated from WSDL.
type OperationNajdiRizeniResponse struct {
	Output *NajdiRizeniResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for NajdiStavbu.
// OperationNajdiStavbuRequest was auto-generated from WSDL.
type OperationNajdiStavbuRequest struct {
	Input *NajdiStavbuRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for NajdiStavbu.
// OperationNajdiStavbuResponse was auto-generated from WSDL.
type OperationNajdiStavbuResponse struct {
	Output *NajdiStavbuResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// vyhledat implements the Vyhledat interface.
type vyhledat struct {
	cli *soap.Client
}

// NajdiJednotku was auto-generated from WSDL.
func (p *vyhledat) NajdiJednotku(NajdiJednotkuRequest *NajdiJednotkuRequest) (*NajdiJednotkuResponse, error) {
	α := struct {
		OperationNajdiJednotkuRequest `xml:"tns:najdiJednotku"`
	}{
		OperationNajdiJednotkuRequest{
			NajdiJednotkuRequest,
		},
	}

	γ := struct {
		OperationNajdiJednotkuResponse `xml:"najdiJednotkuResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/vyhledat//najdiJednotku", α, &γ); err != nil {
		return nil, err
	}
	return γ.NajdiJednotkuResponse, nil
}

// NajdiListinuVeSbirceListin was auto-generated from WSDL.
func (p *vyhledat) NajdiListinuVeSbirceListin(NajdiListinuVeSbirceListinRequest *NajdiListinuVeSbirceListinRequest) (*NajdiListinuVeSbirceListinResponse, error) {
	α := struct {
		OperationNajdiListinuVeSbirceListinRequest `xml:"tns:najdiListinuVeSbirceListin"`
	}{
		OperationNajdiListinuVeSbirceListinRequest{
			NajdiListinuVeSbirceListinRequest,
		},
	}

	γ := struct {
		OperationNajdiListinuVeSbirceListinResponse `xml:"najdiListinuVeSbirceListinResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/vyhledat//najdiListinu", α, &γ); err != nil {
		return nil, err
	}
	return γ.NajdiListinuVeSbirceListinResponse, nil
}

// NajdiOS was auto-generated from WSDL.
func (p *vyhledat) NajdiOS(NajdiOSRequest *NajdiOSRequest) (*NajdiOSResponse, error) {
	α := struct {
		OperationNajdiOSRequest `xml:"tns:najdiOS"`
	}{
		OperationNajdiOSRequest{
			NajdiOSRequest,
		},
	}

	γ := struct {
		OperationNajdiOSResponse `xml:"najdiOSResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/vyhledat//najdiOS", α, &γ); err != nil {
		return nil, err
	}
	return γ.NajdiOSResponse, nil
}

// NajdiParcelu was auto-generated from WSDL.
func (p *vyhledat) NajdiParcelu(NajdiParceluRequest *NajdiParceluRequest) (*NajdiParceluResponse, error) {
	α := struct {
		OperationNajdiParceluRequest `xml:"tns:najdiParcelu"`
	}{
		OperationNajdiParceluRequest{
			NajdiParceluRequest,
		},
	}

	γ := struct {
		OperationNajdiParceluResponse `xml:"najdiParceluResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/vyhledat//najdiParcelu", α, &γ); err != nil {
		return nil, err
	}
	return γ.NajdiParceluResponse, nil
}

// NajdiPravoStavby was auto-generated from WSDL.
func (p *vyhledat) NajdiPravoStavby(NajdiPravoStavbyRequest *NajdiPravoStavbyRequest) (*NajdiPravoStavbyResponse, error) {
	α := struct {
		OperationNajdiPravoStavbyRequest `xml:"tns:najdiPravoStavby"`
	}{
		OperationNajdiPravoStavbyRequest{
			NajdiPravoStavbyRequest,
		},
	}

	γ := struct {
		OperationNajdiPravoStavbyResponse `xml:"najdiPravoStavbyResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/vyhledat//najdiPravoStavby", α, &γ); err != nil {
		return nil, err
	}
	return γ.NajdiPravoStavbyResponse, nil
}

// NajdiRizeni was auto-generated from WSDL.
func (p *vyhledat) NajdiRizeni(NajdiRizeniRequest *NajdiRizeniRequest) (*NajdiRizeniResponse, error) {
	α := struct {
		OperationNajdiRizeniRequest `xml:"tns:najdiRizeni"`
	}{
		OperationNajdiRizeniRequest{
			NajdiRizeniRequest,
		},
	}

	γ := struct {
		OperationNajdiRizeniResponse `xml:"najdiRizeniResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/vyhledat//najdiRizeni", α, &γ); err != nil {
		return nil, err
	}
	return γ.NajdiRizeniResponse, nil
}

// NajdiStavbu was auto-generated from WSDL.
func (p *vyhledat) NajdiStavbu(NajdiStavbuRequest *NajdiStavbuRequest) (*NajdiStavbuResponse, error) {
	α := struct {
		OperationNajdiStavbuRequest `xml:"tns:najdiStavbu"`
	}{
		OperationNajdiStavbuRequest{
			NajdiStavbuRequest,
		},
	}

	γ := struct {
		OperationNajdiStavbuResponse `xml:"najdiStavbuResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/vyhledat//najdiStavbu", α, &γ); err != nil {
		return nil, err
	}
	return γ.NajdiStavbuResponse, nil
}
