// Code generated by wsdl2go. DO NOT EDIT.

package ciselniksoapbinding

import (
	"github.com/fiorix/wsdl2go/soap"
)

// Namespace was auto-generated from WSDL.
var Namespace = "http://katastr.cuzk.cz/ciselnik/v2.8"

// NewCiselnik creates an initializes a Ciselnik.
func NewCiselnik(cli *soap.Client) Ciselnik {
	return &ciselnik{cli}
}

// Ciselnik was auto-generated from WSDL
// and defines interface for the remote service. Useful for testing.
type Ciselnik interface {
	// SeznamCastiObci was auto-generated from WSDL.
	SeznamCastiObci(SeznamCastiObciRequest *SeznamCastiObciRequest) (*SeznamCastiObciResponse, error)

	// SeznamCharakteristikOS was auto-generated from WSDL.
	SeznamCharakteristikOS(SeznamCharakteristikOSRequest *SeznamCharakteristikOSRequest) (*SeznamCharakteristikOSResponse, error)

	// SeznamCiselniku was auto-generated from WSDL.
	SeznamCiselniku(SeznamCiselnikuRequest *SeznamCiselnikuRequest) (*SeznamCiselnikuResponse, error)

	// SeznamCislovaniParcel was auto-generated from WSDL.
	SeznamCislovaniParcel(SeznamCislovaniParcelRequest *SeznamCislovaniParcelRequest) (*SeznamCislovaniParcelResponse, error)

	// SeznamDruhuPozemku was auto-generated from WSDL.
	SeznamDruhuPozemku(SeznamDruhuPozemkuRequest *SeznamDruhuPozemkuRequest) (*SeznamDruhuPozemkuResponse, error)

	// SeznamHistKU was auto-generated from WSDL.
	SeznamHistKU(SeznamHistKURequest *SeznamHistKURequest) (*SeznamHistKUResponse, error)

	// SeznamKU was auto-generated from WSDL.
	SeznamKU(SeznamKURequest *SeznamKURequest) (*SeznamKUResponse, error)

	// SeznamKraju was auto-generated from WSDL.
	SeznamKraju(SeznamKrajuRequest *SeznamKrajuRequest) (*SeznamKrajuResponse, error)

	// SeznamMestskychCasti was auto-generated from WSDL.
	SeznamMestskychCasti(SeznamMestskychCastiRequest *SeznamMestskychCastiRequest) (*SeznamMestskychCastiResponse, error)

	// SeznamObci was auto-generated from WSDL.
	SeznamObci(SeznamObciRequest *SeznamObciRequest) (*SeznamObciResponse, error)

	// SeznamOkresu was auto-generated from WSDL.
	SeznamOkresu(SeznamOkresuRequest *SeznamOkresuRequest) (*SeznamOkresuResponse, error)

	// SeznamOperaciRizeni was auto-generated from WSDL.
	SeznamOperaciRizeni(SeznamOperaciRizeniRequest *SeznamOperaciRizeniRequest) (*SeznamOperaciRizeniResponse, error)

	// SeznamPracovist was auto-generated from WSDL.
	SeznamPracovist(SeznamPracovistRequest *SeznamPracovistRequest) (*SeznamPracovistResponse, error)

	// SeznamPredmetuRizeni was auto-generated from WSDL.
	SeznamPredmetuRizeni(SeznamPredmetuRizeniRequest *SeznamPredmetuRizeniRequest) (*SeznamPredmetuRizeniResponse, error)

	// SeznamStatu was auto-generated from WSDL.
	SeznamStatu(SeznamStatuRequest *SeznamStatuRequest) (*SeznamStatuResponse, error)

	// SeznamTypParcely was auto-generated from WSDL.
	SeznamTypParcely(SeznamTypParcelyRequest *SeznamTypParcelyRequest) (*SeznamTypParcelyResponse, error)

	// SeznamTypuJednotek was auto-generated from WSDL.
	SeznamTypuJednotek(SeznamTypuJednotekRequest *SeznamTypuJednotekRequest) (*SeznamTypuJednotekResponse, error)

	// SeznamTypuOS was auto-generated from WSDL.
	SeznamTypuOS(SeznamTypuOSRequest *SeznamTypuOSRequest) (*SeznamTypuOSResponse, error)

	// SeznamTypuOperaci was auto-generated from WSDL.
	SeznamTypuOperaci(SeznamTypuOperaciRequest *SeznamTypuOperaciRequest) (*SeznamTypuOperaciResponse, error)

	// SeznamTypuParcel was auto-generated from WSDL.
	SeznamTypuParcel(SeznamTypuParcelRequest *SeznamTypuParcelRequest) (*SeznamTypuParcelResponse, error)

	// SeznamTypuPravnichVztahu was auto-generated from WSDL.
	SeznamTypuPravnichVztahu(SeznamTypuPravnichVztahuRequest *SeznamTypuPravnichVztahuRequest) (*SeznamTypuPravnichVztahuResponse, error)

	// SeznamTypuRizeni was auto-generated from WSDL.
	SeznamTypuRizeni(SeznamTypuRizeniRequest *SeznamTypuRizeniRequest) (*SeznamTypuRizeniResponse, error)

	// SeznamTypuStaveb was auto-generated from WSDL.
	SeznamTypuStaveb(SeznamTypuStavebRequest *SeznamTypuStavebRequest) (*SeznamTypuStavebResponse, error)

	// SeznamUcelu was auto-generated from WSDL.
	SeznamUcelu(SeznamUceluRequest *SeznamUceluRequest) (*SeznamUceluResponse, error)

	// SeznamUceluPS was auto-generated from WSDL.
	SeznamUceluPS(SeznamUceluPSRequest *SeznamUceluPSRequest) (*SeznamUceluPSResponse, error)

	// SeznamUlic was auto-generated from WSDL.
	SeznamUlic(SeznamUlicRequest *SeznamUlicRequest) (*SeznamUlicResponse, error)

	// SeznamUrceniVymery was auto-generated from WSDL.
	SeznamUrceniVymery(SeznamUrceniVymeryRequest *SeznamUrceniVymeryRequest) (*SeznamUrceniVymeryResponse, error)

	// SeznamVyuzitiJednotky was auto-generated from WSDL.
	SeznamVyuzitiJednotky(SeznamVyuzitiJednotkyRequest *SeznamVyuzitiJednotkyRequest) (*SeznamVyuzitiJednotkyResponse, error)

	// SeznamVyuzitiPozemku was auto-generated from WSDL.
	SeznamVyuzitiPozemku(SeznamVyuzitiPozemkuRequest *SeznamVyuzitiPozemkuRequest) (*SeznamVyuzitiPozemkuResponse, error)

	// SeznamVyuzitiStavby was auto-generated from WSDL.
	SeznamVyuzitiStavby(SeznamVyuzitiStavbyRequest *SeznamVyuzitiStavbyRequest) (*SeznamVyuzitiStavbyResponse, error)

	// SeznamZdrojuCislovaniZE was auto-generated from WSDL.
	SeznamZdrojuCislovaniZE(SeznamZdrojuCislovaniZERequest *SeznamZdrojuCislovaniZERequest) (*SeznamZdrojuCislovaniZEResponse, error)

	// SeznamZprav was auto-generated from WSDL.
	SeznamZprav(SeznamZpravRequest *SeznamZpravRequest) (*SeznamZpravResponse, error)

	// SeznamZpusobOchrany was auto-generated from WSDL.
	SeznamZpusobOchrany(SeznamZpusobOchranyRequest *SeznamZpusobOchranyRequest) (*SeznamZpusobOchranyResponse, error)
}

// Operation wrapper for SeznamCastiObci.
// OperationSeznamCastiObciRequest was auto-generated from WSDL.
type OperationSeznamCastiObciRequest struct {
	Input *SeznamCastiObciRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamCastiObci.
// OperationSeznamCastiObciResponse was auto-generated from WSDL.
type OperationSeznamCastiObciResponse struct {
	Output *SeznamCastiObciResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamCharakteristikOS.
// OperationSeznamCharakteristikOSRequest was auto-generated from
// WSDL.
type OperationSeznamCharakteristikOSRequest struct {
	Input *SeznamCharakteristikOSRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamCharakteristikOS.
// OperationSeznamCharakteristikOSResponse was auto-generated from
// WSDL.
type OperationSeznamCharakteristikOSResponse struct {
	Input *SeznamCharakteristikOSResponse `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamCiselniku.
// OperationSeznamCiselnikuRequest was auto-generated from WSDL.
type OperationSeznamCiselnikuRequest struct {
	Input *SeznamCiselnikuRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamCiselniku.
// OperationSeznamCiselnikuResponse was auto-generated from WSDL.
type OperationSeznamCiselnikuResponse struct {
	Output *SeznamCiselnikuResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamCislovaniParcel.
// OperationSeznamCislovaniParcelRequest was auto-generated from
// WSDL.
type OperationSeznamCislovaniParcelRequest struct {
	Input *SeznamCislovaniParcelRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamCislovaniParcel.
// OperationSeznamCislovaniParcelResponse was auto-generated from
// WSDL.
type OperationSeznamCislovaniParcelResponse struct {
	Output *SeznamCislovaniParcelResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamDruhuPozemku.
// OperationSeznamDruhuPozemkuRequest was auto-generated from WSDL.
type OperationSeznamDruhuPozemkuRequest struct {
	Input *SeznamDruhuPozemkuRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamDruhuPozemku.
// OperationSeznamDruhuPozemkuResponse was auto-generated from
// WSDL.
type OperationSeznamDruhuPozemkuResponse struct {
	Output *SeznamDruhuPozemkuResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamHistKU.
// OperationSeznamHistKURequest was auto-generated from WSDL.
type OperationSeznamHistKURequest struct {
	Input *SeznamHistKURequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamHistKU.
// OperationSeznamHistKUResponse was auto-generated from WSDL.
type OperationSeznamHistKUResponse struct {
	Output *SeznamHistKUResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamKU.
// OperationSeznamKURequest was auto-generated from WSDL.
type OperationSeznamKURequest struct {
	Input *SeznamKURequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamKU.
// OperationSeznamKUResponse was auto-generated from WSDL.
type OperationSeznamKUResponse struct {
	Output *SeznamKUResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamKraju.
// OperationSeznamKrajuRequest was auto-generated from WSDL.
type OperationSeznamKrajuRequest struct {
	Input *SeznamKrajuRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamKraju.
// OperationSeznamKrajuResponse was auto-generated from WSDL.
type OperationSeznamKrajuResponse struct {
	Output *SeznamKrajuResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamMestskychCasti.
// OperationSeznamMestskychCastiRequest was auto-generated from
// WSDL.
type OperationSeznamMestskychCastiRequest struct {
	Input *SeznamMestskychCastiRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamMestskychCasti.
// OperationSeznamMestskychCastiResponse was auto-generated from
// WSDL.
type OperationSeznamMestskychCastiResponse struct {
	Output *SeznamMestskychCastiResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamObci.
// OperationSeznamObciRequest was auto-generated from WSDL.
type OperationSeznamObciRequest struct {
	Input *SeznamObciRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamObci.
// OperationSeznamObciResponse was auto-generated from WSDL.
type OperationSeznamObciResponse struct {
	Output *SeznamObciResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamOkresu.
// OperationSeznamOkresuRequest was auto-generated from WSDL.
type OperationSeznamOkresuRequest struct {
	Input *SeznamOkresuRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamOkresu.
// OperationSeznamOkresuResponse was auto-generated from WSDL.
type OperationSeznamOkresuResponse struct {
	Output *SeznamOkresuResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamOperaciRizeni.
// OperationSeznamOperaciRizeniRequest was auto-generated from
// WSDL.
type OperationSeznamOperaciRizeniRequest struct {
	Input *SeznamOperaciRizeniRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamOperaciRizeni.
// OperationSeznamOperaciRizeniResponse was auto-generated from
// WSDL.
type OperationSeznamOperaciRizeniResponse struct {
	Output *SeznamOperaciRizeniResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamPracovist.
// OperationSeznamPracovistRequest was auto-generated from WSDL.
type OperationSeznamPracovistRequest struct {
	Input *SeznamPracovistRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamPracovist.
// OperationSeznamPracovistResponse was auto-generated from WSDL.
type OperationSeznamPracovistResponse struct {
	Output *SeznamPracovistResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamPredmetuRizeni.
// OperationSeznamPredmetuRizeniRequest was auto-generated from
// WSDL.
type OperationSeznamPredmetuRizeniRequest struct {
	Input *SeznamPredmetuRizeniRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamPredmetuRizeni.
// OperationSeznamPredmetuRizeniResponse was auto-generated from
// WSDL.
type OperationSeznamPredmetuRizeniResponse struct {
	Output *SeznamPredmetuRizeniResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamStatu.
// OperationSeznamStatuRequest was auto-generated from WSDL.
type OperationSeznamStatuRequest struct {
	Input *SeznamStatuRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamStatu.
// OperationSeznamStatuResponse was auto-generated from WSDL.
type OperationSeznamStatuResponse struct {
	Output *SeznamStatuResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamTypParcely.
// OperationSeznamTypParcelyRequest was auto-generated from WSDL.
type OperationSeznamTypParcelyRequest struct {
	Input *SeznamTypParcelyRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamTypParcely.
// OperationSeznamTypParcelyResponse was auto-generated from WSDL.
type OperationSeznamTypParcelyResponse struct {
	Input *SeznamTypParcelyResponse `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamTypuJednotek.
// OperationSeznamTypuJednotekRequest was auto-generated from WSDL.
type OperationSeznamTypuJednotekRequest struct {
	Input *SeznamTypuJednotekRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamTypuJednotek.
// OperationSeznamTypuJednotekResponse was auto-generated from
// WSDL.
type OperationSeznamTypuJednotekResponse struct {
	Output *SeznamTypuJednotekResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamTypuOS.
// OperationSeznamTypuOSRequest was auto-generated from WSDL.
type OperationSeznamTypuOSRequest struct {
	Input *SeznamTypuOSRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamTypuOS.
// OperationSeznamTypuOSResponse was auto-generated from WSDL.
type OperationSeznamTypuOSResponse struct {
	Output *SeznamTypuOSResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamTypuOperaci.
// OperationSeznamTypuOperaciRequest was auto-generated from WSDL.
type OperationSeznamTypuOperaciRequest struct {
	Input *SeznamTypuOperaciRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamTypuOperaci.
// OperationSeznamTypuOperaciResponse was auto-generated from WSDL.
type OperationSeznamTypuOperaciResponse struct {
	Output *SeznamTypuOperaciResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamTypuParcel.
// OperationSeznamTypuParcelRequest was auto-generated from WSDL.
type OperationSeznamTypuParcelRequest struct {
	Input *SeznamTypuParcelRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamTypuParcel.
// OperationSeznamTypuParcelResponse was auto-generated from WSDL.
type OperationSeznamTypuParcelResponse struct {
	Output *SeznamTypuParcelResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamTypuPravnichVztahu.
// OperationSeznamTypuPravnichVztahuRequest was auto-generated
// from WSDL.
type OperationSeznamTypuPravnichVztahuRequest struct {
	Input *SeznamTypuPravnichVztahuRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamTypuPravnichVztahu.
// OperationSeznamTypuPravnichVztahuResponse was auto-generated
// from WSDL.
type OperationSeznamTypuPravnichVztahuResponse struct {
	Output *SeznamTypuPravnichVztahuResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamTypuRizeni.
// OperationSeznamTypuRizeniRequest was auto-generated from WSDL.
type OperationSeznamTypuRizeniRequest struct {
	Input *SeznamTypuRizeniRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamTypuRizeni.
// OperationSeznamTypuRizeniResponse was auto-generated from WSDL.
type OperationSeznamTypuRizeniResponse struct {
	Output *SeznamTypuRizeniResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamTypuStaveb.
// OperationSeznamTypuStavebRequest was auto-generated from WSDL.
type OperationSeznamTypuStavebRequest struct {
	Input *SeznamTypuStavebRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamTypuStaveb.
// OperationSeznamTypuStavebResponse was auto-generated from WSDL.
type OperationSeznamTypuStavebResponse struct {
	Output *SeznamTypuStavebResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamUcelu.
// OperationSeznamUceluRequest was auto-generated from WSDL.
type OperationSeznamUceluRequest struct {
	Input *SeznamUceluRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamUcelu.
// OperationSeznamUceluResponse was auto-generated from WSDL.
type OperationSeznamUceluResponse struct {
	Output *SeznamUceluResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamUceluPS.
// OperationSeznamUceluPSRequest was auto-generated from WSDL.
type OperationSeznamUceluPSRequest struct {
	Input *SeznamUceluPSRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamUceluPS.
// OperationSeznamUceluPSResponse was auto-generated from WSDL.
type OperationSeznamUceluPSResponse struct {
	Input *SeznamUceluPSResponse `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamUlic.
// OperationSeznamUlicRequest was auto-generated from WSDL.
type OperationSeznamUlicRequest struct {
	Input *SeznamUlicRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamUlic.
// OperationSeznamUlicResponse was auto-generated from WSDL.
type OperationSeznamUlicResponse struct {
	Output *SeznamUlicResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamUrceniVymery.
// OperationSeznamUrceniVymeryRequest was auto-generated from WSDL.
type OperationSeznamUrceniVymeryRequest struct {
	Input *SeznamUrceniVymeryRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamUrceniVymery.
// OperationSeznamUrceniVymeryResponse was auto-generated from
// WSDL.
type OperationSeznamUrceniVymeryResponse struct {
	Output *SeznamUrceniVymeryResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamVyuzitiJednotky.
// OperationSeznamVyuzitiJednotkyRequest was auto-generated from
// WSDL.
type OperationSeznamVyuzitiJednotkyRequest struct {
	Input *SeznamVyuzitiJednotkyRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamVyuzitiJednotky.
// OperationSeznamVyuzitiJednotkyResponse was auto-generated from
// WSDL.
type OperationSeznamVyuzitiJednotkyResponse struct {
	Output *SeznamVyuzitiJednotkyResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamVyuzitiPozemku.
// OperationSeznamVyuzitiPozemkuRequest was auto-generated from
// WSDL.
type OperationSeznamVyuzitiPozemkuRequest struct {
	Input *SeznamVyuzitiPozemkuRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamVyuzitiPozemku.
// OperationSeznamVyuzitiPozemkuResponse was auto-generated from
// WSDL.
type OperationSeznamVyuzitiPozemkuResponse struct {
	Output *SeznamVyuzitiPozemkuResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamVyuzitiStavby.
// OperationSeznamVyuzitiStavbyRequest was auto-generated from
// WSDL.
type OperationSeznamVyuzitiStavbyRequest struct {
	Input *SeznamVyuzitiStavbyRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamVyuzitiStavby.
// OperationSeznamVyuzitiStavbyResponse was auto-generated from
// WSDL.
type OperationSeznamVyuzitiStavbyResponse struct {
	Output *SeznamVyuzitiStavbyResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamZdrojuCislovaniZE.
// OperationSeznamZdrojuCislovaniZERequest was auto-generated from
// WSDL.
type OperationSeznamZdrojuCislovaniZERequest struct {
	Input *SeznamZdrojuCislovaniZERequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamZdrojuCislovaniZE.
// OperationSeznamZdrojuCislovaniZEResponse was auto-generated
// from WSDL.
type OperationSeznamZdrojuCislovaniZEResponse struct {
	Output *SeznamZdrojuCislovaniZEResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamZprav.
// OperationSeznamZpravRequest was auto-generated from WSDL.
type OperationSeznamZpravRequest struct {
	Input *SeznamZpravRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamZprav.
// OperationSeznamZpravResponse was auto-generated from WSDL.
type OperationSeznamZpravResponse struct {
	Output *SeznamZpravResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// Operation wrapper for SeznamZpusobOchrany.
// OperationSeznamZpusobOchranyRequest was auto-generated from
// WSDL.
type OperationSeznamZpusobOchranyRequest struct {
	Input *SeznamZpusobOchranyRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for SeznamZpusobOchrany.
// OperationSeznamZpusobOchranyResponse was auto-generated from
// WSDL.
type OperationSeznamZpusobOchranyResponse struct {
	Output *SeznamZpusobOchranyResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// ciselnik implements the Ciselnik interface.
type ciselnik struct {
	cli *soap.Client
}

// SeznamCastiObci was auto-generated from WSDL.
func (p *ciselnik) SeznamCastiObci(SeznamCastiObciRequest *SeznamCastiObciRequest) (*SeznamCastiObciResponse, error) {
	α := struct {
		OperationSeznamCastiObciRequest `xml:"tns:seznamCastiObci"`
	}{
		OperationSeznamCastiObciRequest{
			SeznamCastiObciRequest,
		},
	}

	γ := struct {
		OperationSeznamCastiObciResponse `xml:"seznamCastiObciResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamCastiObci", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamCastiObciResponse, nil
}

// SeznamCharakteristikOS was auto-generated from WSDL.
func (p *ciselnik) SeznamCharakteristikOS(SeznamCharakteristikOSRequest *SeznamCharakteristikOSRequest) (*SeznamCharakteristikOSResponse, error) {
	α := struct {
		OperationSeznamCharakteristikOSRequest `xml:"tns:seznamCharakteristikOS"`
	}{
		OperationSeznamCharakteristikOSRequest{
			SeznamCharakteristikOSRequest,
		},
	}

	γ := struct {
		OperationSeznamCharakteristikOSResponse `xml:"seznamCharakteristikOSResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamCharakteristikOS", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamCharakteristikOSResponse, nil
}

// SeznamCiselniku was auto-generated from WSDL.
func (p *ciselnik) SeznamCiselniku(SeznamCiselnikuRequest *SeznamCiselnikuRequest) (*SeznamCiselnikuResponse, error) {
	α := struct {
		OperationSeznamCiselnikuRequest `xml:"tns:seznamCiselniku"`
	}{
		OperationSeznamCiselnikuRequest{
			SeznamCiselnikuRequest,
		},
	}

	γ := struct {
		OperationSeznamCiselnikuResponse `xml:"seznamCiselnikuResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamCiselniku", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamCiselnikuResponse, nil
}

// SeznamCislovaniParcel was auto-generated from WSDL.
func (p *ciselnik) SeznamCislovaniParcel(SeznamCislovaniParcelRequest *SeznamCislovaniParcelRequest) (*SeznamCislovaniParcelResponse, error) {
	α := struct {
		OperationSeznamCislovaniParcelRequest `xml:"tns:seznamCislovaniParcel"`
	}{
		OperationSeznamCislovaniParcelRequest{
			SeznamCislovaniParcelRequest,
		},
	}

	γ := struct {
		OperationSeznamCislovaniParcelResponse `xml:"seznamCislovaniParcelResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamCislovaniParcel", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamCislovaniParcelResponse, nil
}

// SeznamDruhuPozemku was auto-generated from WSDL.
func (p *ciselnik) SeznamDruhuPozemku(SeznamDruhuPozemkuRequest *SeznamDruhuPozemkuRequest) (*SeznamDruhuPozemkuResponse, error) {
	α := struct {
		OperationSeznamDruhuPozemkuRequest `xml:"tns:seznamDruhuPozemku"`
	}{
		OperationSeznamDruhuPozemkuRequest{
			SeznamDruhuPozemkuRequest,
		},
	}

	γ := struct {
		OperationSeznamDruhuPozemkuResponse `xml:"seznamDruhuPozemkuResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamDruhuPozemku", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamDruhuPozemkuResponse, nil
}

// SeznamHistKU was auto-generated from WSDL.
func (p *ciselnik) SeznamHistKU(SeznamHistKURequest *SeznamHistKURequest) (*SeznamHistKUResponse, error) {
	α := struct {
		OperationSeznamHistKURequest `xml:"tns:seznamHistKU"`
	}{
		OperationSeznamHistKURequest{
			SeznamHistKURequest,
		},
	}

	γ := struct {
		OperationSeznamHistKUResponse `xml:"seznamHistKUResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamHistKU", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamHistKUResponse, nil
}

// SeznamKU was auto-generated from WSDL.
func (p *ciselnik) SeznamKU(SeznamKURequest *SeznamKURequest) (*SeznamKUResponse, error) {
	α := struct {
		OperationSeznamKURequest `xml:"tns:seznamKU"`
	}{
		OperationSeznamKURequest{
			SeznamKURequest,
		},
	}

	γ := struct {
		OperationSeznamKUResponse `xml:"seznamKUResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamKU", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamKUResponse, nil
}

// SeznamKraju was auto-generated from WSDL.
func (p *ciselnik) SeznamKraju(SeznamKrajuRequest *SeznamKrajuRequest) (*SeznamKrajuResponse, error) {
	α := struct {
		OperationSeznamKrajuRequest `xml:"tns:seznamKraju"`
	}{
		OperationSeznamKrajuRequest{
			SeznamKrajuRequest,
		},
	}

	γ := struct {
		OperationSeznamKrajuResponse `xml:"seznamKrajuResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamKraju", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamKrajuResponse, nil
}

// SeznamMestskychCasti was auto-generated from WSDL.
func (p *ciselnik) SeznamMestskychCasti(SeznamMestskychCastiRequest *SeznamMestskychCastiRequest) (*SeznamMestskychCastiResponse, error) {
	α := struct {
		OperationSeznamMestskychCastiRequest `xml:"tns:seznamMestskychCasti"`
	}{
		OperationSeznamMestskychCastiRequest{
			SeznamMestskychCastiRequest,
		},
	}

	γ := struct {
		OperationSeznamMestskychCastiResponse `xml:"seznamMestskychCastiResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamMestskychCasti", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamMestskychCastiResponse, nil
}

// SeznamObci was auto-generated from WSDL.
func (p *ciselnik) SeznamObci(SeznamObciRequest *SeznamObciRequest) (*SeznamObciResponse, error) {
	α := struct {
		OperationSeznamObciRequest `xml:"tns:seznamObci"`
	}{
		OperationSeznamObciRequest{
			SeznamObciRequest,
		},
	}

	γ := struct {
		OperationSeznamObciResponse `xml:"seznamObciResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamObci", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamObciResponse, nil
}

// SeznamOkresu was auto-generated from WSDL.
func (p *ciselnik) SeznamOkresu(SeznamOkresuRequest *SeznamOkresuRequest) (*SeznamOkresuResponse, error) {
	α := struct {
		OperationSeznamOkresuRequest `xml:"tns:seznamOkresu"`
	}{
		OperationSeznamOkresuRequest{
			SeznamOkresuRequest,
		},
	}

	γ := struct {
		OperationSeznamOkresuResponse `xml:"seznamOkresuResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamOkresu", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamOkresuResponse, nil
}

// SeznamOperaciRizeni was auto-generated from WSDL.
func (p *ciselnik) SeznamOperaciRizeni(SeznamOperaciRizeniRequest *SeznamOperaciRizeniRequest) (*SeznamOperaciRizeniResponse, error) {
	α := struct {
		OperationSeznamOperaciRizeniRequest `xml:"tns:seznamOperaciRizeni"`
	}{
		OperationSeznamOperaciRizeniRequest{
			SeznamOperaciRizeniRequest,
		},
	}

	γ := struct {
		OperationSeznamOperaciRizeniResponse `xml:"seznamOperaciRizeniResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamOperaciRizeni", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamOperaciRizeniResponse, nil
}

// SeznamPracovist was auto-generated from WSDL.
func (p *ciselnik) SeznamPracovist(SeznamPracovistRequest *SeznamPracovistRequest) (*SeznamPracovistResponse, error) {
	α := struct {
		OperationSeznamPracovistRequest `xml:"tns:seznamPracovist"`
	}{
		OperationSeznamPracovistRequest{
			SeznamPracovistRequest,
		},
	}

	γ := struct {
		OperationSeznamPracovistResponse `xml:"seznamPracovistResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamPracovist", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamPracovistResponse, nil
}

// SeznamPredmetuRizeni was auto-generated from WSDL.
func (p *ciselnik) SeznamPredmetuRizeni(SeznamPredmetuRizeniRequest *SeznamPredmetuRizeniRequest) (*SeznamPredmetuRizeniResponse, error) {
	α := struct {
		OperationSeznamPredmetuRizeniRequest `xml:"tns:seznamPredmetuRizeni"`
	}{
		OperationSeznamPredmetuRizeniRequest{
			SeznamPredmetuRizeniRequest,
		},
	}

	γ := struct {
		OperationSeznamPredmetuRizeniResponse `xml:"seznamPredmetuRizeniResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamPredmetuRizeni", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamPredmetuRizeniResponse, nil
}

// SeznamStatu was auto-generated from WSDL.
func (p *ciselnik) SeznamStatu(SeznamStatuRequest *SeznamStatuRequest) (*SeznamStatuResponse, error) {
	α := struct {
		OperationSeznamStatuRequest `xml:"tns:seznamStatu"`
	}{
		OperationSeznamStatuRequest{
			SeznamStatuRequest,
		},
	}

	γ := struct {
		OperationSeznamStatuResponse `xml:"seznamStatuResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamStatu", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamStatuResponse, nil
}

// SeznamTypParcely was auto-generated from WSDL.
func (p *ciselnik) SeznamTypParcely(SeznamTypParcelyRequest *SeznamTypParcelyRequest) (*SeznamTypParcelyResponse, error) {
	α := struct {
		OperationSeznamTypParcelyRequest `xml:"tns:seznamTypParcely"`
	}{
		OperationSeznamTypParcelyRequest{
			SeznamTypParcelyRequest,
		},
	}

	γ := struct {
		OperationSeznamTypParcelyResponse `xml:"seznamTypParcelyResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamTypParcely", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamTypParcelyResponse, nil
}

// SeznamTypuJednotek was auto-generated from WSDL.
func (p *ciselnik) SeznamTypuJednotek(SeznamTypuJednotekRequest *SeznamTypuJednotekRequest) (*SeznamTypuJednotekResponse, error) {
	α := struct {
		OperationSeznamTypuJednotekRequest `xml:"tns:seznamTypuJednotek"`
	}{
		OperationSeznamTypuJednotekRequest{
			SeznamTypuJednotekRequest,
		},
	}

	γ := struct {
		OperationSeznamTypuJednotekResponse `xml:"seznamTypuJednotekResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamTypuJednotek", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamTypuJednotekResponse, nil
}

// SeznamTypuOS was auto-generated from WSDL.
func (p *ciselnik) SeznamTypuOS(SeznamTypuOSRequest *SeznamTypuOSRequest) (*SeznamTypuOSResponse, error) {
	α := struct {
		OperationSeznamTypuOSRequest `xml:"tns:seznamTypuOS"`
	}{
		OperationSeznamTypuOSRequest{
			SeznamTypuOSRequest,
		},
	}

	γ := struct {
		OperationSeznamTypuOSResponse `xml:"seznamTypuOSResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamTypuOS", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamTypuOSResponse, nil
}

// SeznamTypuOperaci was auto-generated from WSDL.
func (p *ciselnik) SeznamTypuOperaci(SeznamTypuOperaciRequest *SeznamTypuOperaciRequest) (*SeznamTypuOperaciResponse, error) {
	α := struct {
		OperationSeznamTypuOperaciRequest `xml:"tns:seznamTypuOperaci"`
	}{
		OperationSeznamTypuOperaciRequest{
			SeznamTypuOperaciRequest,
		},
	}

	γ := struct {
		OperationSeznamTypuOperaciResponse `xml:"seznamTypuOperaciResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamTypuOperaci", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamTypuOperaciResponse, nil
}

// SeznamTypuParcel was auto-generated from WSDL.
func (p *ciselnik) SeznamTypuParcel(SeznamTypuParcelRequest *SeznamTypuParcelRequest) (*SeznamTypuParcelResponse, error) {
	α := struct {
		OperationSeznamTypuParcelRequest `xml:"tns:seznamTypuParcel"`
	}{
		OperationSeznamTypuParcelRequest{
			SeznamTypuParcelRequest,
		},
	}

	γ := struct {
		OperationSeznamTypuParcelResponse `xml:"seznamTypuParcelResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamTypuParcel", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamTypuParcelResponse, nil
}

// SeznamTypuPravnichVztahu was auto-generated from WSDL.
func (p *ciselnik) SeznamTypuPravnichVztahu(SeznamTypuPravnichVztahuRequest *SeznamTypuPravnichVztahuRequest) (*SeznamTypuPravnichVztahuResponse, error) {
	α := struct {
		OperationSeznamTypuPravnichVztahuRequest `xml:"tns:seznamTypuPravnichVztahu"`
	}{
		OperationSeznamTypuPravnichVztahuRequest{
			SeznamTypuPravnichVztahuRequest,
		},
	}

	γ := struct {
		OperationSeznamTypuPravnichVztahuResponse `xml:"seznamTypuPravnichVztahuResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamTypuPravnichVztahu", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamTypuPravnichVztahuResponse, nil
}

// SeznamTypuRizeni was auto-generated from WSDL.
func (p *ciselnik) SeznamTypuRizeni(SeznamTypuRizeniRequest *SeznamTypuRizeniRequest) (*SeznamTypuRizeniResponse, error) {
	α := struct {
		OperationSeznamTypuRizeniRequest `xml:"tns:seznamTypuRizeni"`
	}{
		OperationSeznamTypuRizeniRequest{
			SeznamTypuRizeniRequest,
		},
	}

	γ := struct {
		OperationSeznamTypuRizeniResponse `xml:"seznamTypuRizeniResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamTypuRizeni", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamTypuRizeniResponse, nil
}

// SeznamTypuStaveb was auto-generated from WSDL.
func (p *ciselnik) SeznamTypuStaveb(SeznamTypuStavebRequest *SeznamTypuStavebRequest) (*SeznamTypuStavebResponse, error) {
	α := struct {
		OperationSeznamTypuStavebRequest `xml:"tns:seznamTypuStaveb"`
	}{
		OperationSeznamTypuStavebRequest{
			SeznamTypuStavebRequest,
		},
	}

	γ := struct {
		OperationSeznamTypuStavebResponse `xml:"seznamTypuStavebResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamTypuStaveb", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamTypuStavebResponse, nil
}

// SeznamUcelu was auto-generated from WSDL.
func (p *ciselnik) SeznamUcelu(SeznamUceluRequest *SeznamUceluRequest) (*SeznamUceluResponse, error) {
	α := struct {
		OperationSeznamUceluRequest `xml:"tns:seznamUcelu"`
	}{
		OperationSeznamUceluRequest{
			SeznamUceluRequest,
		},
	}

	γ := struct {
		OperationSeznamUceluResponse `xml:"seznamUceluResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamUcelu", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamUceluResponse, nil
}

// SeznamUceluPS was auto-generated from WSDL.
func (p *ciselnik) SeznamUceluPS(SeznamUceluPSRequest *SeznamUceluPSRequest) (*SeznamUceluPSResponse, error) {
	α := struct {
		OperationSeznamUceluPSRequest `xml:"tns:seznamUceluPS"`
	}{
		OperationSeznamUceluPSRequest{
			SeznamUceluPSRequest,
		},
	}

	γ := struct {
		OperationSeznamUceluPSResponse `xml:"seznamUceluPSResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamUceluPS", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamUceluPSResponse, nil
}

// SeznamUlic was auto-generated from WSDL.
func (p *ciselnik) SeznamUlic(SeznamUlicRequest *SeznamUlicRequest) (*SeznamUlicResponse, error) {
	α := struct {
		OperationSeznamUlicRequest `xml:"tns:seznamUlic"`
	}{
		OperationSeznamUlicRequest{
			SeznamUlicRequest,
		},
	}

	γ := struct {
		OperationSeznamUlicResponse `xml:"seznamUlicResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamUlic", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamUlicResponse, nil
}

// SeznamUrceniVymery was auto-generated from WSDL.
func (p *ciselnik) SeznamUrceniVymery(SeznamUrceniVymeryRequest *SeznamUrceniVymeryRequest) (*SeznamUrceniVymeryResponse, error) {
	α := struct {
		OperationSeznamUrceniVymeryRequest `xml:"tns:seznamUrceniVymery"`
	}{
		OperationSeznamUrceniVymeryRequest{
			SeznamUrceniVymeryRequest,
		},
	}

	γ := struct {
		OperationSeznamUrceniVymeryResponse `xml:"seznamUrceniVymeryResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamUrceniVymery", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamUrceniVymeryResponse, nil
}

// SeznamVyuzitiJednotky was auto-generated from WSDL.
func (p *ciselnik) SeznamVyuzitiJednotky(SeznamVyuzitiJednotkyRequest *SeznamVyuzitiJednotkyRequest) (*SeznamVyuzitiJednotkyResponse, error) {
	α := struct {
		OperationSeznamVyuzitiJednotkyRequest `xml:"tns:seznamVyuzitiJednotky"`
	}{
		OperationSeznamVyuzitiJednotkyRequest{
			SeznamVyuzitiJednotkyRequest,
		},
	}

	γ := struct {
		OperationSeznamVyuzitiJednotkyResponse `xml:"seznamVyuzitiJednotkyResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamVyuzitiJednotky", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamVyuzitiJednotkyResponse, nil
}

// SeznamVyuzitiPozemku was auto-generated from WSDL.
func (p *ciselnik) SeznamVyuzitiPozemku(SeznamVyuzitiPozemkuRequest *SeznamVyuzitiPozemkuRequest) (*SeznamVyuzitiPozemkuResponse, error) {
	α := struct {
		OperationSeznamVyuzitiPozemkuRequest `xml:"tns:seznamVyuzitiPozemku"`
	}{
		OperationSeznamVyuzitiPozemkuRequest{
			SeznamVyuzitiPozemkuRequest,
		},
	}

	γ := struct {
		OperationSeznamVyuzitiPozemkuResponse `xml:"seznamVyuzitiPozemkuResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamVyuzitiPozemku", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamVyuzitiPozemkuResponse, nil
}

// SeznamVyuzitiStavby was auto-generated from WSDL.
func (p *ciselnik) SeznamVyuzitiStavby(SeznamVyuzitiStavbyRequest *SeznamVyuzitiStavbyRequest) (*SeznamVyuzitiStavbyResponse, error) {
	α := struct {
		OperationSeznamVyuzitiStavbyRequest `xml:"tns:seznamVyuzitiStavby"`
	}{
		OperationSeznamVyuzitiStavbyRequest{
			SeznamVyuzitiStavbyRequest,
		},
	}

	γ := struct {
		OperationSeznamVyuzitiStavbyResponse `xml:"seznamVyuzitiStavbyResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamVyuzitiStavby", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamVyuzitiStavbyResponse, nil
}

// SeznamZdrojuCislovaniZE was auto-generated from WSDL.
func (p *ciselnik) SeznamZdrojuCislovaniZE(SeznamZdrojuCislovaniZERequest *SeznamZdrojuCislovaniZERequest) (*SeznamZdrojuCislovaniZEResponse, error) {
	α := struct {
		OperationSeznamZdrojuCislovaniZERequest `xml:"tns:seznamZdrojuCislovaniZE"`
	}{
		OperationSeznamZdrojuCislovaniZERequest{
			SeznamZdrojuCislovaniZERequest,
		},
	}

	γ := struct {
		OperationSeznamZdrojuCislovaniZEResponse `xml:"seznamZdrojuCislovaniZEResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamZdrojuCislovaniZE", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamZdrojuCislovaniZEResponse, nil
}

// SeznamZprav was auto-generated from WSDL.
func (p *ciselnik) SeznamZprav(SeznamZpravRequest *SeznamZpravRequest) (*SeznamZpravResponse, error) {
	α := struct {
		OperationSeznamZpravRequest `xml:"tns:seznamZprav"`
	}{
		OperationSeznamZpravRequest{
			SeznamZpravRequest,
		},
	}

	γ := struct {
		OperationSeznamZpravResponse `xml:"seznamZpravResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamZprav", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamZpravResponse, nil
}

// SeznamZpusobOchrany was auto-generated from WSDL.
func (p *ciselnik) SeznamZpusobOchrany(SeznamZpusobOchranyRequest *SeznamZpusobOchranyRequest) (*SeznamZpusobOchranyResponse, error) {
	α := struct {
		OperationSeznamZpusobOchranyRequest `xml:"tns:seznamZpusobOchrany"`
	}{
		OperationSeznamZpusobOchranyRequest{
			SeznamZpusobOchranyRequest,
		},
	}

	γ := struct {
		OperationSeznamZpusobOchranyResponse `xml:"seznamZpusobOchranyResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/ciselnik/seznamZpusobOchrany", α, &γ); err != nil {
		return nil, err
	}
	return γ.SeznamZpusobOchranyResponse, nil
}
