// Code generated by wsdl2go. DO NOT EDIT.

package enxsoapbinding

import (
	"github.com/fiorix/wsdl2go/soap"
)

// Namespace was auto-generated from WSDL.
var Namespace = "http://katastr.cuzk.cz/enx/v2.2"

// NewEnx creates an initializes a Enx.
func NewEnx(cli *soap.Client) Enx {
	return &enx{cli}
}

// Enx was auto-generated from WSDL
// and defines interface for the remote service. Useful for testing.
type Enx interface {
	// ZalozNavrh was auto-generated from WSDL.
	ZalozNavrh(ZalozNavrhRequest *ZalozNavrhRequest) (*ZalozNavrhResponse, error)
}

// Operation wrapper for ZalozNavrh.
// OperationZalozNavrhRequest was auto-generated from WSDL.
type OperationZalozNavrhRequest struct {
	Input *ZalozNavrhRequest `xml:"input,omitempty" json:"input,omitempty" yaml:"input,omitempty"`
}

// Operation wrapper for ZalozNavrh.
// OperationZalozNavrhResponse was auto-generated from WSDL.
type OperationZalozNavrhResponse struct {
	Output *ZalozNavrhResponse `xml:"output,omitempty" json:"output,omitempty" yaml:"output,omitempty"`
}

// enx implements the Enx interface.
type enx struct {
	cli *soap.Client
}

// ZalozNavrh was auto-generated from WSDL.
func (p *enx) ZalozNavrh(ZalozNavrhRequest *ZalozNavrhRequest) (*ZalozNavrhResponse, error) {
	α := struct {
		OperationZalozNavrhRequest `xml:"tns:zalozNavrh"`
	}{
		OperationZalozNavrhRequest{
			ZalozNavrhRequest,
		},
	}

	γ := struct {
		OperationZalozNavrhResponse `xml:"zalozNavrhResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("http://katastr.cuzk.cz/enx//zalozNavrh", α, &γ); err != nil {
		return nil, err
	}
	return γ.ZalozNavrhResponse, nil
}
